# 도커 컨테이너 내부에서 실행될 때 사용
spring:
  # MySQL 데이터베이스 설정
  datasource:
    url: ${PRODUCT_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  # Elasticsearch 설정
  # elasticsearch:
  #   uris: http://els-svc-dev.dev.svc.cluster.local:9200

  kafka:
    bootstrap-servers:
      - kafka-svc-dev.dev.svc.cluster.local:9090
    consumer:
      group-id: product-service
      properties:
        allow.auto.create.topics: false

  data:
    redis:
      host: redis-svc-dev.dev.svc.cluster.local
      port: 6379
      timeout: 500ms
      lettuce:
        pool:
          max-active: 5
        shutdown-timeout: 100ms
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        enabled: ${OPENAI_EMBEDDING_ENABLED}
        options:
          model: text-embedding-3-large
          dimensions: 3072
      chat:
        options:
          model: gpt-4.1
          temperature: 0.6

api:
  user:
    base-url: http://auth-svc-dev.dev.svc.cluster.local:8084


logging:
  level:
    root: info

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      base-url: https://${AWS_S3_BUCKET}.s3.${AWS_REGION:ap-northeast-2}.amazonaws.com
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-svc-dev.dev.svc.cluster.local:9411/api/v2/spans
  server:
    port: 8881
# Qdrant 설정
qdrant:
  host: qdrant-svc-dev.dev.svc.cluster.local
  port: 6334
  collection-name: products

swagger:
  servers:
    - "http://localhost"