apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config-prod
data:
  PRODUCT_DB_URL: jdbc:mysql://product-db-svc-prod:3311/product_db
  SPRING_PROFILES_ACTIVE : prod
  OPENAI_EMBEDDING_ENABLED: "false"