apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-dpy-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-dev
  template:
    metadata:
      annotations:
        # 이 Pod를 스크랩하도록 Prometheus에게 지시
        prometheus.io/scrape: "true"
        # 메트릭 경로 지정
        prometheus.io/path: "/actuator/prometheus"
        # 메트릭 포트 지정 (Service targetPort와 일치)
        prometheus.io/port: "8881"
      labels:
        app: gateway-dev
    spec:
      containers:
        - name: gateway-pod-dev
          image: gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: gateway-config-dev
            - secretRef:
                name: secret-common-dev
      restartPolicy: Always