spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "http://localhost/login/oauth2/code/{registrationId}"
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name,email,profile_image
            redirect-uri: "http://localhost/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
            provider: naver
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: ${AUTH_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers:
      - http://kafka-svc-dev.dev.svc.cluster.local:9090
    consumer:
      group-id: user-service
      properties:
        allow.auto.create.topics: false

#  redis 설정
  data:
    redis:
      host: redis-svc-dev.dev.svc.cluster.local
      port: 6379
      timeout: 60000ms

#external:
#  user-service:
#    url: http://auth-svc-dev.dev.svc.cluster.local:8084

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    com.ll.auth.handler: INFO

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-svc-dev.dev.svc.cluster.local:9411/api/v2/spans
  server:
    port: 8881
swagger:
  servers:
    - "http://localhost"
