apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-dpy-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-prod
  template:
    metadata:
      labels:
        app: zipkin-prod
    spec:
      containers:
        - name: zipkin-pod-prod
          image: openzipkin/zipkin
          ports:
            - containerPort: 9411
          # In-Memory 저장소이므로 별도의 환경 변수 설정은 필요하지 않습니다.
          # 운영 환경에서는 STORAGE_TYPE 등을 추가해야 합니다.
          resources:
            limits:
              cpu: "300m"
              memory: "312Mi"
            requests:
              cpu: "150m"
              memory: "200Mi"
          envFrom:
            - configMapRef:
                name: zipkin-config-prod

