apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productdb-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # productdb에 필요한 예상 용량으로 조정하세요 (예: 50Gi)
      storage: 3Gi