apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-prod
data:
  prometheus.yml: |
    global:
      # 15초마다 타겟을 스크랩(Scrape)합니다.
      scrape_interval: 15s
    
    scrape_configs:
      # 1. 자신(프로메테우스 서버)을 모니터링합니다.
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # 2. 쿠버네티스 노드와 Pod의 상태를 모니터링합니다. 
      # 이 예시는 간단한 테스트를 위해 Kubelet을 타겟으로 설정합니다.
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/$1/proxy/metrics
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      # 3. 모든 Spring Boot 애플리케이션 모니터링
      - job_name: 'microservices-spring-boot'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          # Pod에 'prometheus.io/scrape: "true"' 레이블이 있는 엔드포인트만 유지합니다.
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"
          
          # 메트릭 경로를 /actuator/prometheus로 설정
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: "(.+)"

          # 포트 이름이 'metrics'인 경우에만 타겟을 유지합니다.
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: "metrics"

          # __address__의 포트 부분을 '8881'로 덮어씁니다.
          # (Pod IP는 유지하고 포트만 변경)
          - source_labels: [__address__]
            action: replace
            target_label: __address__
            regex: "(.+):(\\d+)" # IP와 포트 캡처
            replacement: "$1:8881" # IP는 유지하고 포트를 8881로 변경
          
          # job 이름을 Service 이름으로 대체하여 그룹화합니다.
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: job
          
          # Pod의 app 레이블을 인스턴스 레이블로 추가
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            target_label: instance