apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dpy-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-prod
  template:
    metadata:
      labels:
        app: prometheus-prod
    spec:
      containers:
        - name: prometheus-pod-prod
          image: prom/prometheus:v2.45.0 # 안정적인 버전 사용 권장
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: "300m" # 1 vCPU
              memory: "400Mi"  # 메모리 제한
            requests:
              cpu: "200m"  # 0.5 vCPU 보장 요청
              memory: "300Mi"  # 메모리 보장 요청
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        # ConfigMap을 마운트하여 설정 파일을 사용합니다.
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config-prod
        # Prometheus 데이터 저장을 위한 임시 볼륨입니다. (운영 환경에서는 PVC 사용)
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data-pvc