apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-dpy-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prod
  template:
    metadata:
      labels:
        app: nginx-prod
    spec:
      containers:
        - name: nginx-pod-prod
          image: jc21/nginx-proxy-manager:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 81
              name: admin
            - containerPort: 443
              name: https
          volumeMounts:
            - name: data
              mountPath: /data
            - name: letsencrypt
              mountPath: /etc/letsencrypt
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nginx-data-pvc
        - name: letsencrypt
          persistentVolumeClaim:
            claimName: nginx-letsencrypt-pvc