ext {
    springAiVersion = "1.1.0"
}
description = 'products'


springBoot {
    mainClass = 'com.ll.products.ProductsApplication'  // 실제 존재하는 main class
}
dependencies {
    // implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework:spring-aspects'

    implementation 'org.springframework.kafka:spring-kafka'
    // QueryDSL
    implementation "com.querydsl:querydsl-jpa:${querydslVersion}:jakarta"
    annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jakarta"
    annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
    annotationProcessor 'jakarta.persistence:jakarta.persistence-api'

    implementation 'org.springframework.ai:spring-ai-starter-vector-store-qdrant'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    runtimeOnly 'com.h2database:h2'
    runtimeOnly "mysql:mysql-connector-java:${mysqlVersion}"

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'io.micrometer:micrometer-tracing-bridge-brave'
    implementation 'io.zipkin.reporter2:zipkin-reporter-brave'
    implementation 'io.micrometer:micrometer-registry-prometheus'

    // AWS S3
    implementation "software.amazon.awssdk:s3:2.39.3"

    // Qdrant
    implementation 'io.qdrant:client:1.13.0'

    // gRPC
    implementation 'io.grpc:grpc-netty-shaded:1.68.1'
    implementation 'io.grpc:grpc-protobuf:1.68.1'
    implementation 'io.grpc:grpc-stub:1.68.1'

    // env 파일 읽기
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'

    // redis 관련 implementation
    implementation("org.springframework.boot:spring-boot-starter-data-redis")
    implementation("org.springframework.boot:spring-boot-starter-cache")

    // swagger
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:${springdocVersion}")

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // 테스트 컨테이너
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "org.testcontainers:mysql"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.register("prepareKotlinBuildScriptModel"){}
