name: CI-TEST-WORKFLOW

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  code-test:
    name: 코드 테스트
    runs-on: ubuntu-latest

    steps:
      - name: 브랜치 체크아웃
        uses: actions/checkout@v5

      # [추가] Testcontainers 캐시 설정
      - name: Testcontainers Cache
        uses: actions/cache@v4
        with:
          path: ~/.testcontainers
          key: ${{ runner.os }}-testcontainers-${{ hashFiles('build.gradle*') }}
          restore-keys: ${{ runner.os }}-testcontainers-

      - name: JDK 세팅
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Pre-pull MySQL Docker Image
        run: docker pull mysql:8.2.0

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 서비스 테스트 실행
        run: ./gradlew :${{inputs.service-name}}:test --no-daemon -Dspring.profiles.active=ci-test --info
