# 메인브랜치에 push 시, product 서비스를 배포, 롤링 업데이트 하는 작업
name: product-CD
on:
  push:
    branches:
#      - test/main
      - main
    paths:
      - 'products/**' # product 폴더 변경 시
      - 'core/**' # core 폴더 변경 시
permissions:
  contents: read
jobs:
  deploying:
    uses: ./.github/workflows/cd-workflow.yml
    secrets: inherit
    with:
      service-name: product

